### ISSUE TITLE
featureform error on custom widget config

### ISSUE THREAD

**Issue by HeatherHillers** [roam-qgis/Roam#21]
for following config:

```
title: Tree Inspection (Sample)
description: Sample tree inspection module
forms:
   trees:
      capabilities: 
         capture:
            label: Add Tree
         move:
         edit:
      label: Trees
      layer: trees
      type: custom
      widgets: 
         TreeCollectionDialog:
            name: Add Tree
            widget: custom
            field: photo
            rememberlastvalue: True
            hidden: False
```

Capture Fails with:
Traceback (most recent call last):
  File "roam\dataentrywidget.pyc", line 182, in continueload
  File "roam\featureform.pyc", line 301, in bind
TypeError: string indices must be integers, not str

This featureform code with these debug messages:
        widgetsconfig = self.formconfig['widgets']
        utils.log(str(widgetsconfig))
        for config in widgetsconfig:
            utils.log(".."+str(config)+ "..")
:301            widgettype = config['widget"]

yields:

DEBUG - 2013-12-17 12:41:56,221 - featureform-loadsavedvalues:81 - C:\Users\hil\AppData\Roaming\Roam\trees20120923001707500.json
DEBUG - 2013-12-17 12:41:56,244 - featureform-bind:298 - OrderedDict([('TreeCollectionDialog', OrderedDict([('name', 'Add Tree'), ('widget', 'custom'), ('field', 'photo'), ('rememberlastvalue', True), ('hidden', False)]))])
DEBUG - 2013-12-17 12:41:56,244 - featureform-bind:300 - ..TreeCollectionDialog.

It Looks like the code should read
for name, config in widgetsconfig:

This is also an issue at featureform.py:117

My Settings are probably not entirely right, since I'm piecing them together as I go from errors, but I don't think they are causing the problem here.
