### ISSUE TITLE
are custom forms implemented?

### ISSUE THREAD

**Issue by HeatherHillers** [roam-qgis/Roam#38]
I have successfully launched a Project with an autogenerated data entry widget and saved data with it.  I would like to try a custom form from Qt Designer, as was the example in QMap.  I would like to know if this is implemented fully in Roam. 

 I see the code is there to load the form.ui, and that seems to be happening successfully for a simple QWidget with a single drop down menu At least, within the code, self.featureform sees the child widget for my drop down. But, when it Comes to actually loading the widget, I get the following:
File "roam\mainwindow.pyc", line 542, in captureData 
File "roam\dataentrywidget.pyc", line 284, in openform 
File "roam\featureform.pyc", line 218, in setupui 
KeyError: 'widgets'

and featureform.setupui doesn't look like it's meant to handle anything but forms built from the config file.  Has custom been dropped as an Option?

my Settings.config (I have modified a bit to allow for Output to a second layer.  My modifications don't effect the form loading, though)

```
   Gebiet_Gewaessermeisterei:             # Polygon shape save to second table
      layer: Gebiet_Gewaessermeisterei   # Layer name in QGIS project
      captureMode: data
      outputLayer: eingabe_gwm
      fieldmap:
         NEWFIELD: name
         GM_NR: gw_nr
      label: 'Poly Geo' # Label shown in Roam interface
      type: 'custom'  # Form type. Can be 'auto'
      display: |    # Display expression show in the info panel
         [% "name" % ]
```
